server {
    server_name _;
    listen 80 default_server;
    error_log  /var/log/nginx/client-error.log;
    access_log /var/log/nginx/client-access.log;

    root /app/browser;

    # Default to Dutch
    location / {
        index index.html;
        try_files $uri $uri/index.html /index.html;
    }

    location /graphql {
        include /etc/nginx/conf.d/proxy/nginx-proxy.conf;
    }

    location /api {
        include /etc/nginx/conf.d/proxy/nginx-proxy.conf;
    }

    location /admin {
        include /etc/nginx/conf.d/proxy/nginx-proxy.conf;
    }
}
