name: WebAuthn CD

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  get_sha:
    name: Get short SHA for image tags
    runs-on: ubuntu-latest
    outputs:
      sha_short: ${{ steps.get_sha.outputs.sha_short }}
    steps:
      - uses: actions/checkout@v4
      - id: get_sha
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> "$GITHUB_OUTPUT"

  determine_buildable:
    name: Determine buildable apps
    runs-on: ubuntu-latest
    outputs:
      buildable: ${{ steps.determine_buildable.outputs.buildable }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - run: npm ci
      - run: npx nx show projects --with-target serve --json
      - id: determine_buildable
        run: echo "buildable=$(npx nx show projects --with-target serve --json)" >> "$GITHUB_OUTPUT"

  build-image:
    name: Build image
    needs: [determine_buildable]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        app: ${{fromJson(needs.determine_buildable.outputs.buildable)}}
    steps:
      - uses: actions/checkout@v4
      - run: docker compose build ${{matrix.app}}
      - run: docker save -o ${{matrix.app}}-image.tar ghcr.io/ionaru/webauthn-demo/${{matrix.app}}:latest
      - uses: actions/upload-artifact@v4
        with:
          name: ${{matrix.app}}-image
          path: ${{matrix.app}}-image.tar
          retention-days: 1

  push-image:
    name: Push image
    if: github.event_name == 'push'
    needs: [get_sha, determine_buildable]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app: ${{fromJson(needs.determine_buildable.outputs.buildable)}}
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: ${{matrix.app}}-image
      - run: docker load -i ${{matrix.app}}-image.tar
      - run: docker tag ghcr.io/ionaru/webauthn-demo/${{matrix.app}}:latest ghcr.io/ionaru/webauthn-demo/${{matrix.app}}:${{needs.get_sha.outputs.sha_short}}
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: docker push -a ghcr.io/ionaru/webauthn-demo/${{matrix.app}}
